# Generated by Django 4.0.4 on 2022-06-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationName', models.CharField(max_length=200, null=True)),
                ('locationName', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('abc', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
