# Generated by Django 4.0.4 on 2022-06-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
