# Generated by Django 4.0.4 on 2022-06-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_admindb_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admindb',
            new_name='Detaildb',
        ),
    ]
