# Generated by Django 4.0.4 on 2022-06-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
