# Generated by Django 4.0.4 on 2022-06-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_contactforjoin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForJoin',
            new_name='ContactForJoinDb',
        ),
    ]
